name: Build and Release
on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build_and_release:
    name: Build and Release (${{ matrix.goos }}_${{ matrix.goarch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -o jamf_webhooks-${{ matrix.goos }}_${{ matrix.goarch }} cmd/main.go
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}

    - name: Release
      uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: jamf_webhooks-${{ matrix.goos }}_${{ matrix.goarch }}
        generate_release_notes: true
